/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package broadband_distribution;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishfaq
 */
public class emp_menu3 extends javax.swing.JInternalFrame {

    /**
     * Creates new form emp_menu3
     */
    public emp_menu3() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0,0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        
        
         try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Broadband;selectMethod=cursor", "sa", "123456");

            Statement statement = connection.createStatement();
            String sql = "SELECT employee.employeeId, employee.eFame,employee.eLastName,employee.eEmail, employee.eEmail,employee.eAdress, employee.ephoneNo,employee.working_area, salary.rank, salary.amount From employee INNER JOIN salary on employee.employeeId= salary.employeeId";

            //  String sql= "SELECT bill.billId, customer.customerId, customer.cName, bill.amount, bill.status,customer.cPhoneNo From bill INNER JOIN customer ON bill.customerId=customer.customerId ";
            ResultSet resultSet = statement
                    .executeQuery(sql);

            while (resultSet.next()) {

                String id = resultSet.getString("employeeId");
                String fname = resultSet.getString("eFame");
                String lname = resultSet.getString("elastName");

                String email = resultSet.getString("eEmail");
                String fAd = resultSet.getString("eAdress");
                String fNo = resultSet.getString("ephoneNo");
                String wa = resultSet.getString("working_area");

                String des = resultSet.getString("rank");
                String sal = resultSet.getString("amount");
                String tData[] = {id, fname, lname, email, fAd, fNo, wa, des, sal};
                DefaultTableModel tbm1 = (DefaultTableModel) delTable.getModel();
                tbm1.addRow(tData);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        area = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        mail = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        pos = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        sal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        delTable = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        nameF = new javax.swing.JTextField();
        nameL = new javax.swing.JTextField();
        addres = new javax.swing.JTextField();
        phnNo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 540));

        area.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        area.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                areaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                areaFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("ENTER KEYWORDS :");

        jButton4.setBackground(new java.awt.Color(153, 153, 153));
        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("SREACH");

        mail.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        mail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        mail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mailFocusLost(evt);
            }
        });

        jTextField1.setBorder(null);
        jTextField1.setOpaque(false);

        pos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        pos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                posFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                posFocusLost(evt);
            }
        });

        sal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sal.setToolTipText("");
        sal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        sal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                salFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                salFocusLost(evt);
            }
        });

        delTable.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        delTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "First NAME", "Last Name", "EMAIL", "ADDRESS", "CONTACT NO", "WORKING AREA", "DESIGNATION", "SALARY"
            }
        ));
        delTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(delTable);

        jButton6.setBackground(new java.awt.Color(0, 203, 133));
        jButton6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton6.setText("UPDATE");

        jButton8.setBackground(new java.awt.Color(0, 203, 133));
        jButton8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton8.setText("DELETE");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        nameF.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nameF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFFocusLost(evt);
            }
        });
        nameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFActionPerformed(evt);
            }
        });

        nameL.setEditable(false);
        nameL.setBackground(new java.awt.Color(255, 255, 255));
        nameL.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        nameL.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        nameL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameLFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameLFocusLost(evt);
            }
        });

        addres.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        addres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addres.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addresFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addresFocusLost(evt);
            }
        });

        phnNo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        phnNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        phnNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phnNoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                phnNoFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("SERACH BY :");

        id.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        id.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        id.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                idFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                idFocusLost(evt);
            }
        });

        jComboBox1.setBackground(new java.awt.Color(0, 153, 255));
        jComboBox1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NAME", "ID" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 203, 133));
        jButton3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jButton3.setText("REFRESH");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("FirstName");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("LAST NAME");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("EMAIL");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("PHONE NO");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("WORKING AREA");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("POSITION");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel10.setText("ADDRESS");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel11.setText("SALARY");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel5))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(addres, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel11))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nameL, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(phnNo)
                            .addComponent(sal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(163, 163, 163)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton4))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(pos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 64, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(jButton8)
                .addGap(58, 58, 58)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(nameF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nameL, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(phnNo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addres, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        
        try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection connection = DriverManager.getConnection(
                    "jdbc:sqlserver://localhost:1433;databaseName=Broadband;selectMethod=cursor", "sa", "123456");

            Statement statement = connection.createStatement();
            String sql = "SELECT employee.employeeId, employee.eFame,employee.eLastName,employee.eEmail, employee.eEmail,employee.eAdress, employee.ephoneNo,employee.working_area, salary.rank, salary.amount From employee INNER JOIN salary on employee.employeeId= salary.employeeId";

            //  String sql= "SELECT bill.billId, customer.customerId, customer.cName, bill.amount, bill.status,customer.cPhoneNo From bill INNER JOIN customer ON bill.customerId=customer.customerId ";
            ResultSet resultSet = statement
                    .executeQuery(sql);

            while (resultSet.next()) {

                String id = resultSet.getString("employeeId");
                String fname = resultSet.getString("eFame");
                String lname = resultSet.getString("elastName");

                String email = resultSet.getString("eEmail");
                String fAd = resultSet.getString("eAdress");
                String fNo = resultSet.getString("ephoneNo");
                String wa = resultSet.getString("working_area");

                String des = resultSet.getString("rank");
                String sal = resultSet.getString("amount");
                String tData[] = {id, fname, lname, email, fAd, fNo, wa, des, sal};
                DefaultTableModel tbm1 = (DefaultTableModel) delTable.getModel();
                tbm1.addRow(tData);

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void idFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusLost
        // TODO add your handling code here:
        if(id.getText().equals(""))
        {
            id.setText("ID");
        }
    }//GEN-LAST:event_idFocusLost

    private void idFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_idFocusGained
        // TODO add your handling code here:
        if(id.getText().equals("ID"))
        {
            id.setText("");
        }
    }//GEN-LAST:event_idFocusGained

    private void phnNoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phnNoFocusLost
        // TODO add your handling code here:
        if(phnNo.getText().equals(""))
        {
            phnNo.setText("PHONE NO");
        }
    }//GEN-LAST:event_phnNoFocusLost

    private void phnNoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phnNoFocusGained
        // TODO add your handling code here:
        if(phnNo.getText().equals("PHONE NO"))
        {
            phnNo.setText("");
        }
    }//GEN-LAST:event_phnNoFocusGained

    private void addresFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addresFocusLost
        // TODO add your handling code here:
        if(addres.getText().equals(""))
        {
            addres.setText("ADDRESS");
        }
    }//GEN-LAST:event_addresFocusLost

    private void addresFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addresFocusGained
        // TODO add your handling code here:
        if(addres.getText().equals("ADDRESS"))
        {
            addres.setText("");
        }
    }//GEN-LAST:event_addresFocusGained

    private void nameLFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameLFocusLost
        // TODO add your handling code here:
        if(nameL.getText().equals(""))
        {
            nameL.setText("LAST NAME");
        }
    }//GEN-LAST:event_nameLFocusLost

    private void nameLFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameLFocusGained
        // TODO add your handling code here:
        if(nameL.getText().equals("LAST NAME"))
        {
            nameL.setText("");
        }
    }//GEN-LAST:event_nameLFocusGained

    private void nameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFActionPerformed

    private void nameFFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFFocusLost
        // TODO add your handling code here:
        if(nameF.getText().equals(""))
        {
            nameF.setText("FirstName");
        }
    }//GEN-LAST:event_nameFFocusLost

    private void nameFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFFocusGained
        // TODO add your handling code here:

        if(nameF.getText().equals("FirstName"))
        {
            nameF.setText("");
        }
    }//GEN-LAST:event_nameFFocusGained

    private void delTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delTableMouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel tbm1 = (DefaultTableModel) delTable.getModel();

        String tid = tbm1.getValueAt(delTable.getSelectedRow(), 0).toString();

        String fName = tbm1.getValueAt(delTable.getSelectedRow(), 1).toString();
        String lName = tbm1.getValueAt(delTable.getSelectedRow(), 2).toString();
        String email = tbm1.getValueAt(delTable.getSelectedRow(), 3).toString();
        String add = tbm1.getValueAt(delTable.getSelectedRow(), 4).toString();
        String con = tbm1.getValueAt(delTable.getSelectedRow(), 5).toString();

        String wa = tbm1.getValueAt(delTable.getSelectedRow(), 6).toString();

        String rank = tbm1.getValueAt(delTable.getSelectedRow(), 7).toString();

        String salary = tbm1.getValueAt(delTable.getSelectedRow(), 8).toString();

        id.setText(tid);
        nameF.setText(fName);
        nameL.setText(lName);
        mail.setText(email);
        addres.setText(add);
        phnNo.setText(con);
        area.setText(wa);
        pos.setText(rank);
        sal.setText(salary);
    }//GEN-LAST:event_delTableMouseClicked

    private void salFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salFocusLost
        // TODO add your handling code here:
        if(sal.getText().equals(""))
        {
            sal.setText("SALARY");
        }
    }//GEN-LAST:event_salFocusLost

    private void salFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salFocusGained
        // TODO add your handling code here:
        if(sal.getText().equals("SALARY"))
        {
            sal.setText("");
        }
    }//GEN-LAST:event_salFocusGained

    private void posFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posFocusLost
        // TODO add your handling code here:
        if(pos.getText().equals(""))
        {
            pos.setText("POSITION");
        }
    }//GEN-LAST:event_posFocusLost

    private void posFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_posFocusGained
        // TODO add your handling code here:
        if(pos.getText().equals("POSITION"))
        {
            pos.setText("");
        }
    }//GEN-LAST:event_posFocusGained

    private void mailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusLost
        // TODO add your handling code here:
        if(mail.getText().equals(""))
        {
            mail.setText("EMAIL");
        }
    }//GEN-LAST:event_mailFocusLost

    private void mailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFocusGained
        // TODO add your handling code here:

        if(mail.getText().equals("EMAIL"))
        {
            mail.setText("");
        }
    }//GEN-LAST:event_mailFocusGained

    private void areaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaFocusLost
        // TODO add your handling code here:

        if(area.getText().equals(""))
        {
            area.setText("WORKING AREA");
        }
    }//GEN-LAST:event_areaFocusLost

    private void areaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_areaFocusGained
        // TODO add your handling code here:
        if(area.getText().equals("WORKING AREA"))
        {
            area.setText("");
        }
    }//GEN-LAST:event_areaFocusGained

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        
         String fname = "",lname="", temail = "", taddress = "", customerId = "", wa="", rank="";
        int tNo,s;
        DefaultTableModel defaultTableModel = (DefaultTableModel) delTable.getModel();

        if (delTable.getSelectedRowCount() == 1) {

            fname = nameF.getText();
            lname= nameL.getText();
            temail = mail.getText();
            taddress = addres.getText();
            tNo = Integer.parseInt(phnNo.getText());
            wa=area.getText();
            rank= pos.getText();
             s = Integer.parseInt(sal.getText());
           //   Float sa= Float.parseFloat(s);
     //   DecimalFormat df= new DecimalFormat("0.00");
     //   df.setMaximumFractionDigits(2);
     //   s= df.format(sa);

            int row = delTable.getSelectedRow();
            customerId = defaultTableModel.getValueAt(row, 0).toString();

            try {
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                Connection connection = DriverManager.getConnection(
                        "jdbc:sqlserver://localhost:1433;databaseName=Broadband;selectMethod=cursor", "sa", "123456");

                    Statement statement = connection.createStatement();
            String sql = "DELETE FROM salary WHERE employeeId = " + Integer.parseInt(customerId) + ";";
                    //String sql = "DELETE FROM employee WHERE employeeId = " + Integer.parseInt(customerId) + ";";
                  
              //   String sql = "DELETE FROM employee WHERE employeeId =(SELECT amount,rank from salary WHERE employeeId = " + Integer.parseInt(customerId) + " );";

            //   String sql = "Delete  FROM employee INNER JOIN salary on employee.employeeId= salary.employeeId WHERE employeeId = " + Integer.parseInt(customerId) + ";";

               
              //  String sql = "DELETE FROM employee WHERE EXISTS(SELECT * FROM salary where salary.employeeId= employee.employeeId AND  salary.employeeId = " + Integer.parseInt(customerId) + ");";
    //   String sql = "DELETE FROM employee WHERE EXISTS(SELECT * FROM salary where salary.employeeId= employee.employeeId) where employeeId =" + Integer.parseInt(customerId) + ";";

                
                    PreparedStatement prepare = connection.prepareStatement(sql);

                    prepare.executeUpdate();
                    
                     String sql2 = "DELETE FROM employee WHERE employeeId = " + Integer.parseInt(customerId) + ";";
            PreparedStatement prepare1 = connection.prepareStatement(sql);

                    prepare1.executeUpdate();
 DefaultTableModel tbm = (DefaultTableModel) delTable.getModel();
                tbm.setRowCount(0);
                    JOptionPane.showMessageDialog(this, "Deleted Successfully");
                    


                
                connection.close();
            } catch (SQLException ex) {
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            if (delTable.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Table Empty");

            } else {
                JOptionPane.showMessageDialog(this, "Please select a roe for delete. ");
            }

        }
    }//GEN-LAST:event_jButton8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addres;
    private javax.swing.JTextField area;
    private javax.swing.JTable delTable;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mail;
    private javax.swing.JTextField nameF;
    private javax.swing.JTextField nameL;
    private javax.swing.JTextField phnNo;
    private javax.swing.JTextField pos;
    private javax.swing.JTextField sal;
    // End of variables declaration//GEN-END:variables
}
